export type WordEntry = { word: string; meaning: string; pos: string; syn: string[]; ant: string[]; level: string; tags: string[] };
export const WORD_BANK: WordEntry[] = [
  { word: 'abundant', meaning: 'plentiful; more than enough', pos: 'adj', syn: ['plentiful', 'ample'], ant: ['scarce', 'limited'], level: 'medium', tags: ['common11plus'] },
  { word: 'accomplish', meaning: 'to successfully achieve a goal', pos: 'verb', syn: ['achieve', 'complete'], ant: ['fail', 'abandon'], level: 'medium', tags: ['common11plus'] },
  { word: 'accurate', meaning: 'correct and without error', pos: 'adj', syn: ['correct', 'precise'], ant: ['inaccurate', 'wrong'], level: 'easy', tags: ['common11plus'] },
  { word: 'adept', meaning: 'very skilled at something', pos: 'adj', syn: ['skilful', 'proficient'], ant: ['clumsy', 'inept'], level: 'medium', tags: ['common11plus'] },
  { word: 'adjacent', meaning: 'next to or adjoining', pos: 'adj', syn: ['next', 'neighbouring'], ant: ['distant', 'separate'], level: 'medium', tags: ['common11plus'] },
  { word: 'admire', meaning: 'to respect and approve of', pos: 'verb', syn: ['respect', 'appreciate'], ant: ['despise', 'scorn'], level: 'easy', tags: ['common11plus'] },
  { word: 'adventurous', meaning: 'willing to try new and exciting things', pos: 'adj', syn: ['bold', 'daring'], ant: ['cautious', 'timid'], level: 'medium', tags: ['common11plus'] },
  { word: 'affectionate', meaning: 'showing fondness or love', pos: 'adj', syn: ['loving', 'caring'], ant: ['cold', 'distant'], level: 'easy', tags: ['common11plus'] },
  { word: 'agile', meaning: 'able to move quickly and easily', pos: 'adj', syn: ['nimble', 'spry'], ant: ['clumsy', 'slow'], level: 'medium', tags: ['common11plus'] },
  { word: 'alert', meaning: 'quick to notice and react', pos: 'adj', syn: ['watchful', 'attentive'], ant: ['drowsy', 'oblivious'], level: 'easy', tags: ['common11plus'] },
  { word: 'alleviate', meaning: 'to make something less severe', pos: 'verb', syn: ['ease', 'relieve'], ant: ['worsen', 'aggravate'], level: 'medium', tags: ['common11plus'] },
  { word: 'amiable', meaning: 'friendly and pleasant', pos: 'adj', syn: ['friendly', 'genial'], ant: ['hostile', 'unfriendly'], level: 'medium', tags: ['common11plus'] },
  { word: 'ancient', meaning: 'very old', pos: 'adj', syn: ['old', 'antique'], ant: ['modern', 'new'], level: 'easy', tags: ['common11plus'] },
  { word: 'anxious', meaning: 'worried and uneasy', pos: 'adj', syn: ['worried', 'nervous'], ant: ['calm', 'confident'], level: 'easy', tags: ['common11plus'] },
  { word: 'apprehensive', meaning: 'anxious about something that might happen', pos: 'adj', syn: ['fearful', 'uneasy'], ant: ['assured', 'bold'], level: 'medium', tags: ['common11plus'] },
  { word: 'ardent', meaning: 'showing strong feelings', pos: 'adj', syn: ['passionate', 'eager'], ant: ['cold', 'indifferent'], level: 'hard', tags: ['common11plus'] },
  { word: 'arduous', meaning: 'needing a lot of effort', pos: 'adj', syn: ['difficult', 'laborious'], ant: ['easy', 'simple'], level: 'hard', tags: ['common11plus'] },
  { word: 'articulate', meaning: 'able to express ideas clearly', pos: 'adj', syn: ['eloquent', 'fluent'], ant: ['inarticulate', 'tongue-tied'], level: 'hard', tags: ['common11plus'] },
  { word: 'astonish', meaning: 'to surprise greatly', pos: 'verb', syn: ['amaze', 'astound'], ant: ['bore', 'calm'], level: 'medium', tags: ['common11plus'] },
  { word: 'attentive', meaning: 'paying close attention', pos: 'adj', syn: ['observant', 'alert'], ant: ['distracted', 'inattentive'], level: 'easy', tags: ['common11plus'] },
  { word: 'audacious', meaning: 'showing a willingness to take bold risks', pos: 'adj', syn: ['bold', 'daring'], ant: ['meek', 'timid'], level: 'hard', tags: ['common11plus'] },
  { word: 'authentic', meaning: 'genuine and true', pos: 'adj', syn: ['genuine', 'real'], ant: ['fake', 'bogus'], level: 'medium', tags: ['common11plus'] },
  { word: 'averse', meaning: 'strongly disliking', pos: 'adj', syn: ['opposed', 'unwilling'], ant: ['keen', 'eager'], level: 'medium', tags: ['common11plus'] },
  { word: 'baffle', meaning: 'to totally confuse', pos: 'verb', syn: ['confuse', 'puzzle'], ant: ['clarify', 'explain'], level: 'medium', tags: ['common11plus'] },
  { word: 'bargain', meaning: 'something bought cheaply', pos: 'noun', syn: ['deal', 'discount'], ant: ['rip-off', 'overcharge'], level: 'easy', tags: ['common11plus'] },
  { word: 'benevolent', meaning: 'kind and generous', pos: 'adj', syn: ['kind', 'charitable'], ant: ['unkind', 'mean'], level: 'medium', tags: ['common11plus'] },
  { word: 'benign', meaning: 'gentle and harmless', pos: 'adj', syn: ['harmless', 'kindly'], ant: ['harmful', 'malignant'], level: 'hard', tags: ['common11plus'] },
  { word: 'brisk', meaning: 'quick and active', pos: 'adj', syn: ['lively', 'energetic'], ant: ['sluggish', 'slow'], level: 'easy', tags: ['common11plus'] },
  { word: 'burdensome', meaning: 'hard to bear', pos: 'adj', syn: ['onerous', 'troublesome'], ant: ['light', 'easy'], level: 'hard', tags: ['common11plus'] },
  { word: 'candid', meaning: 'truthful and straightforward', pos: 'adj', syn: ['frank', 'honest'], ant: ['guarded', 'secretive'], level: 'medium', tags: ['common11plus'] },
  { word: 'capable', meaning: 'having the ability', pos: 'adj', syn: ['able', 'competent'], ant: ['unable', 'inept'], level: 'easy', tags: ['common11plus'] },
  { word: 'capricious', meaning: 'changing suddenly and often', pos: 'adj', syn: ['fickle', 'unpredictable'], ant: ['steady', 'consistent'], level: 'hard', tags: ['common11plus'] },
  { word: 'captivate', meaning: 'to hold interest completely', pos: 'verb', syn: ['enthral', 'charm'], ant: ['bore', 'repel'], level: 'medium', tags: ['common11plus'] },
  { word: 'cautious', meaning: 'careful to avoid danger', pos: 'adj', syn: ['careful', 'wary'], ant: ['reckless', 'careless'], level: 'easy', tags: ['common11plus'] },
  { word: 'cease', meaning: 'to stop', pos: 'verb', syn: ['halt', 'end'], ant: ['begin', 'continue'], level: 'medium', tags: ['common11plus'] },
  { word: 'cherish', meaning: 'to care deeply for', pos: 'verb', syn: ['treasure', 'value'], ant: ['neglect', 'spurn'], level: 'easy', tags: ['common11plus'] },
  { word: 'coax', meaning: 'to gently persuade', pos: 'verb', syn: ['persuade', 'entice'], ant: ['force', 'deter'], level: 'medium', tags: ['common11plus'] },
  { word: 'coherent', meaning: 'logical and well organised', pos: 'adj', syn: ['logical', 'orderly'], ant: ['confused', 'illogical'], level: 'hard', tags: ['common11plus'] },
  { word: 'commend', meaning: 'to praise formally', pos: 'verb', syn: ['praise', 'applaud'], ant: ['criticise', 'condemn'], level: 'medium', tags: ['common11plus'] },
  { word: 'compassionate', meaning: 'showing sympathy for others', pos: 'adj', syn: ['kind', 'caring'], ant: ['cruel', 'uncaring'], level: 'easy', tags: ['common11plus'] },
  { word: 'competent', meaning: 'having enough skill', pos: 'adj', syn: ['capable', 'able'], ant: ['incapable', 'inept'], level: 'medium', tags: ['common11plus'] },
  { word: 'composed', meaning: 'calm and in control', pos: 'adj', syn: ['calm', 'collected'], ant: ['agitated', 'upset'], level: 'medium', tags: ['common11plus'] },
  { word: 'comprehensive', meaning: 'including everything important', pos: 'adj', syn: ['thorough', 'complete'], ant: ['limited', 'narrow'], level: 'hard', tags: ['common11plus'] },
  { word: 'concise', meaning: 'short and clear', pos: 'adj', syn: ['brief', 'succinct'], ant: ['wordy', 'rambling'], level: 'medium', tags: ['common11plus'] },
  { word: 'confident', meaning: 'feeling sure', pos: 'adj', syn: ['self-assured', 'positive'], ant: ['unsure', 'nervous'], level: 'easy', tags: ['common11plus'] },
  { word: 'conscientious', meaning: 'careful and hardworking', pos: 'adj', syn: ['thorough', 'diligent'], ant: ['careless', 'negligent'], level: 'hard', tags: ['common11plus'] },
  { word: 'consequence', meaning: 'a result or effect', pos: 'noun', syn: ['result', 'outcome'], ant: ['cause', 'source'], level: 'easy', tags: ['common11plus'] },
  { word: 'considerate', meaning: 'thoughtful of others', pos: 'adj', syn: ['thoughtful', 'kind'], ant: ['selfish', 'thoughtless'], level: 'easy', tags: ['common11plus'] },
  { word: 'consistent', meaning: 'acting the same over time', pos: 'adj', syn: ['steady', 'reliable'], ant: ['changeable', 'inconsistent'], level: 'easy', tags: ['common11plus'] },
  { word: 'contemplate', meaning: 'to think about deeply', pos: 'verb', syn: ['ponder', 'consider'], ant: ['dismiss', 'ignore'], level: 'medium', tags: ['common11plus'] },
  { word: 'content', meaning: 'happy and satisfied', pos: 'adj', syn: ['satisfied', 'pleased'], ant: ['discontent', 'unhappy'], level: 'easy', tags: ['common11plus'] },
  { word: 'conventional', meaning: 'following usual practices', pos: 'adj', syn: ['traditional', 'standard'], ant: ['unusual', 'innovative'], level: 'medium', tags: ['common11plus'] },
  { word: 'cordial', meaning: 'warm and friendly', pos: 'adj', syn: ['friendly', 'genial'], ant: ['rude', 'hostile'], level: 'medium', tags: ['common11plus'] },
  { word: 'courageous', meaning: 'brave', pos: 'adj', syn: ['brave', 'valiant'], ant: ['cowardly', 'fearful'], level: 'easy', tags: ['common11plus'] },
  { word: 'courteous', meaning: 'polite and respectful', pos: 'adj', syn: ['polite', 'respectful'], ant: ['rude', 'impolite'], level: 'easy', tags: ['common11plus'] },
  { word: 'credible', meaning: 'believable', pos: 'adj', syn: ['believable', 'plausible'], ant: ['unbelievable', 'doubtful'], level: 'medium', tags: ['common11plus'] },
  { word: 'cunning', meaning: 'clever at getting what you want', pos: 'adj', syn: ['crafty', 'sly'], ant: ['honest', 'naive'], level: 'medium', tags: ['common11plus'] },
  { word: 'dainty', meaning: 'small and delicate', pos: 'adj', syn: ['delicate', 'pretty'], ant: ['coarse', 'clumsy'], level: 'easy', tags: ['common11plus'] },
  { word: 'daring', meaning: 'willing to take risks', pos: 'adj', syn: ['bold', 'adventurous'], ant: ['cowardly', 'fearful'], level: 'medium', tags: ['common11plus'] },
  { word: 'dauntless', meaning: 'fearless', pos: 'adj', syn: ['brave', 'undaunted'], ant: ['afraid', 'timid'], level: 'hard', tags: ['common11plus'] },
  { word: 'deceive', meaning: 'to make someone believe something untrue', pos: 'verb', syn: ['mislead', 'trick'], ant: ['inform', 'enlighten'], level: 'medium', tags: ['common11plus'] },
  { word: 'decisive', meaning: 'able to make decisions quickly', pos: 'adj', syn: ['firm', 'resolute'], ant: ['hesitant', 'indecisive'], level: 'medium', tags: ['common11plus'] },
  { word: 'dedicated', meaning: 'giving a lot of time and energy', pos: 'adj', syn: ['committed', 'devoted'], ant: ['casual', 'uncommitted'], level: 'medium', tags: ['common11plus'] },
  { word: 'defiant', meaning: 'openly resisting', pos: 'adj', syn: ['rebellious', 'insubordinate'], ant: ['obedient', 'compliant'], level: 'medium', tags: ['common11plus'] },
  { word: 'diligent', meaning: 'hardworking and careful', pos: 'adj', syn: ['hardworking', 'assiduous'], ant: ['idle', 'lazy'], level: 'medium', tags: ['common11plus'] },
  { word: 'discreet', meaning: 'careful not to attract attention', pos: 'adj', syn: ['careful', 'tactful'], ant: ['indiscreet', 'blatant'], level: 'hard', tags: ['common11plus'] },
  { word: 'dismal', meaning: 'very gloomy', pos: 'adj', syn: ['gloomy', 'dreary'], ant: ['cheerful', 'bright'], level: 'medium', tags: ['common11plus'] },
  { word: 'dismay', meaning: 'to cause worry and sadness', pos: 'verb', syn: ['distress', 'alarm'], ant: ['encourage', 'reassure'], level: 'medium', tags: ['common11plus'] },
  { word: 'distinct', meaning: 'clearly different', pos: 'adj', syn: ['clear', 'separate'], ant: ['vague', 'similar'], level: 'medium', tags: ['common11plus'] },
  { word: 'diverse', meaning: 'showing variety', pos: 'adj', syn: ['varied', 'mixed'], ant: ['uniform', 'similar'], level: 'medium', tags: ['common11plus'] },
  { word: 'docile', meaning: 'easy to teach or manage', pos: 'adj', syn: ['obedient', 'compliant'], ant: ['headstrong', 'stubborn'], level: 'hard', tags: ['common11plus'] },
  { word: 'drab', meaning: 'dull and colourless', pos: 'adj', syn: ['dull', 'colourless'], ant: ['bright', 'vibrant'], level: 'easy', tags: ['common11plus'] },
  { word: 'durable', meaning: 'able to last a long time', pos: 'adj', syn: ['long-lasting', 'sturdy'], ant: ['fragile', 'weak'], level: 'medium', tags: ['common11plus'] },
  { word: 'earnest', meaning: 'showing sincere conviction', pos: 'adj', syn: ['serious', 'sincere'], ant: ['frivolous', 'insincere'], level: 'medium', tags: ['common11plus'] },
  { word: 'ecstatic', meaning: 'extremely happy', pos: 'adj', syn: ['overjoyed', 'delighted'], ant: ['miserable', 'downcast'], level: 'medium', tags: ['common11plus'] },
  { word: 'eloquent', meaning: 'speaking or writing well', pos: 'adj', syn: ['articulate', 'expressive'], ant: ['tongue-tied', 'mumbling'], level: 'hard', tags: ['common11plus'] },
  { word: 'elusive', meaning: 'hard to find or catch', pos: 'adj', syn: ['slippery', 'evasive'], ant: ['obvious', 'easy'], level: 'hard', tags: ['common11plus'] },
  { word: 'emerge', meaning: 'to come into view', pos: 'verb', syn: ['appear', 'surface'], ant: ['vanish', 'disappear'], level: 'easy', tags: ['common11plus'] },
  { word: 'empathy', meaning: "the ability to understand others' feelings", pos: 'noun', syn: ['understanding', 'compassion'], ant: ['indifference', 'apathy'], level: 'medium', tags: ['common11plus'] },
  { word: 'endeavour', meaning: 'to make a serious effort', pos: 'verb', syn: ['strive', 'attempt'], ant: ['give up', 'neglect'], level: 'medium', tags: ['common11plus'] },
  { word: 'endure', meaning: 'to suffer patiently', pos: 'verb', syn: ['bear', 'withstand'], ant: ['quit', 'surrender'], level: 'medium', tags: ['common11plus'] },
  { word: 'engross', meaning: 'to absorb all attention', pos: 'verb', syn: ['absorb', 'captivate'], ant: ['bore', 'distract'], level: 'medium', tags: ['common11plus'] },
  { word: 'enhance', meaning: 'to improve or add to', pos: 'verb', syn: ['improve', 'boost'], ant: ['diminish', 'weaken'], level: 'medium', tags: ['common11plus'] },
  { word: 'enthral', meaning: 'to hold spellbound', pos: 'verb', syn: ['captivate', 'enchant'], ant: ['bore', 'repel'], level: 'hard', tags: ['common11plus'] },
  { word: 'equitable', meaning: 'fair and impartial', pos: 'adj', syn: ['fair', 'just'], ant: ['unfair', 'biased'], level: 'hard', tags: ['common11plus'] },
  { word: 'evident', meaning: 'easy to see or understand', pos: 'adj', syn: ['obvious', 'clear'], ant: ['hidden', 'unclear'], level: 'easy', tags: ['common11plus'] },
  { word: 'exasperate', meaning: 'to annoy greatly', pos: 'verb', syn: ['annoy', 'irritate'], ant: ['please', 'soothe'], level: 'medium', tags: ['common11plus'] },
  { word: 'exceed', meaning: 'to be greater than', pos: 'verb', syn: ['surpass', 'outstrip'], ant: ['fall short', 'fail'], level: 'medium', tags: ['common11plus'] },
  { word: 'exuberant', meaning: 'full of energy and excitement', pos: 'adj', syn: ['joyful', 'lively'], ant: ['dull', 'sad'], level: 'medium', tags: ['common11plus'] },
  { word: 'factual', meaning: 'based on facts', pos: 'adj', syn: ['accurate', 'true'], ant: ['false', 'fictional'], level: 'easy', tags: ['common11plus'] },
  { word: 'faithful', meaning: 'loyal and true', pos: 'adj', syn: ['loyal', 'devoted'], ant: ['disloyal', 'unfaithful'], level: 'easy', tags: ['common11plus'] },
  { word: 'feeble', meaning: 'very weak', pos: 'adj', syn: ['weak', 'frail'], ant: ['strong', 'robust'], level: 'easy', tags: ['common11plus'] },
  { word: 'fervent', meaning: 'showing strong passion', pos: 'adj', syn: ['passionate', 'ardent'], ant: ['cool', 'apathetic'], level: 'hard', tags: ['common11plus'] },
  { word: 'fickle', meaning: 'changing often', pos: 'adj', syn: ['changeable', 'inconstant'], ant: ['steady', 'reliable'], level: 'hard', tags: ['common11plus'] },
  { word: 'flourish', meaning: 'to grow strongly', pos: 'verb', syn: ['thrive', 'prosper'], ant: ['wither', 'fail'], level: 'medium', tags: ['common11plus'] },
  { word: 'forbid', meaning: 'to refuse to allow', pos: 'verb', syn: ['ban', 'prohibit'], ant: ['permit', 'allow'], level: 'easy', tags: ['common11plus'] },
  { word: 'fortitude', meaning: 'courage in pain or adversity', pos: 'noun', syn: ['courage', 'bravery'], ant: ['cowardice', 'weakness'], level: 'hard', tags: ['common11plus'] },
  { word: 'fragrant', meaning: 'having a pleasant smell', pos: 'adj', syn: ['scented', 'aromatic'], ant: ['stinky', 'odorless'], level: 'easy', tags: ['common11plus'] },
  { word: 'frugal', meaning: 'careful with money', pos: 'adj', syn: ['thrifty', 'economical'], ant: ['wasteful', 'extravagant'], level: 'medium', tags: ['common11plus'] },
  { word: 'gallant', meaning: 'brave and noble', pos: 'adj', syn: ['valiant', 'chivalrous'], ant: ['cowardly', 'unkind'], level: 'medium', tags: ['common11plus'] },
  { word: 'generous', meaning: 'willing to give', pos: 'adj', syn: ['giving', 'charitable'], ant: ['mean', 'selfish'], level: 'easy', tags: ['common11plus'] },
  { word: 'genuine', meaning: 'real and sincere', pos: 'adj', syn: ['authentic', 'real'], ant: ['fake', 'false'], level: 'easy', tags: ['common11plus'] },
  { word: 'gleaming', meaning: 'shining brightly', pos: 'adj', syn: ['shining', 'sparkling'], ant: ['dull', 'matte'], level: 'easy', tags: ['common11plus'] },
  { word: 'glum', meaning: 'sad and gloomy', pos: 'adj', syn: ['sad', 'miserable'], ant: ['cheerful', 'happy'], level: 'easy', tags: ['common11plus'] },
  { word: 'gracious', meaning: 'polite and kind', pos: 'adj', syn: ['courteous', 'kind'], ant: ['rude', 'unkind'], level: 'easy', tags: ['common11plus'] },
  { word: 'gratify', meaning: 'to please or satisfy', pos: 'verb', syn: ['please', 'delight'], ant: ['disappoint', 'upset'], level: 'medium', tags: ['common11plus'] },
  { word: 'gregarious', meaning: 'fond of company', pos: 'adj', syn: ['sociable', 'outgoing'], ant: ['shy', 'solitary'], level: 'hard', tags: ['common11plus'] },
  { word: 'grimy', meaning: 'very dirty', pos: 'adj', syn: ['dirty', 'filthy'], ant: ['clean', 'spotless'], level: 'easy', tags: ['common11plus'] },
  { word: 'gritty', meaning: 'showing courage and resolve', pos: 'adj', syn: ['determined', 'tough'], ant: ['weak', 'spineless'], level: 'hard', tags: ['common11plus'] },
  { word: 'habitual', meaning: 'done often', pos: 'adj', syn: ['regular', 'customary'], ant: ['rare', 'occasional'], level: 'medium', tags: ['common11plus'] },
  { word: 'harmonious', meaning: 'forming a pleasing whole', pos: 'adj', syn: ['balanced', 'tuneful'], ant: ['discordant', 'harsh'], level: 'medium', tags: ['common11plus'] },
  { word: 'hasten', meaning: 'to hurry', pos: 'verb', syn: ['rush', 'accelerate'], ant: ['delay', 'slow'], level: 'medium', tags: ['common11plus'] },
  { word: 'heed', meaning: 'to pay attention to', pos: 'verb', syn: ['listen', 'notice'], ant: ['ignore', 'disregard'], level: 'medium', tags: ['common11plus'] },
  { word: 'hesitant', meaning: 'unsure and slow to act', pos: 'adj', syn: ['uncertain', 'reluctant'], ant: ['eager', 'confident'], level: 'easy', tags: ['common11plus'] },
  { word: 'honourable', meaning: 'deserving respect', pos: 'adj', syn: ['noble', 'respectable'], ant: ['shameful', 'dishonourable'], level: 'medium', tags: ['common11plus'] },
  { word: 'humble', meaning: 'modest and not proud', pos: 'adj', syn: ['modest', 'meek'], ant: ['proud', 'arrogant'], level: 'easy', tags: ['common11plus'] },
  { word: 'humdrum', meaning: 'dull and monotonous', pos: 'adj', syn: ['dull', 'boring'], ant: ['exciting', 'lively'], level: 'medium', tags: ['common11plus'] },
  { word: 'illuminate', meaning: 'to light up', pos: 'verb', syn: ['light', 'brighten'], ant: ['darken', 'dim'], level: 'easy', tags: ['common11plus'] },
  { word: 'impartial', meaning: 'fair and not biased', pos: 'adj', syn: ['fair', 'neutral'], ant: ['biased', 'partial'], level: 'hard', tags: ['common11plus'] },
  { word: 'impede', meaning: 'to slow or block progress', pos: 'verb', syn: ['hinder', 'obstruct'], ant: ['aid', 'assist'], level: 'medium', tags: ['common11plus'] },
  { word: 'impetuous', meaning: 'acting quickly without thought', pos: 'adj', syn: ['rash', 'hasty'], ant: ['cautious', 'careful'], level: 'hard', tags: ['common11plus'] },
  { word: 'imposing', meaning: 'grand and impressive', pos: 'adj', syn: ['grand', 'stately'], ant: ['ordinary', 'humble'], level: 'hard', tags: ['common11plus'] },
  { word: 'improvise', meaning: 'to create without preparation', pos: 'verb', syn: ['ad-lib', 'invent'], ant: ['plan', 'rehearse'], level: 'medium', tags: ['common11plus'] },
  { word: 'incessant', meaning: 'continuing without stopping', pos: 'adj', syn: ['constant', 'endless'], ant: ['occasional', 'intermittent'], level: 'hard', tags: ['common11plus'] },
  { word: 'incline', meaning: 'to feel willing towards', pos: 'verb', syn: ['tend', 'lean'], ant: ['refuse', 'resist'], level: 'medium', tags: ['common11plus'] },
  { word: 'indignant', meaning: 'angry about unfairness', pos: 'adj', syn: ['outraged', 'resentful'], ant: ['pleased', 'content'], level: 'medium', tags: ['common11plus'] },
  { word: 'industrious', meaning: 'hard working', pos: 'adj', syn: ['diligent', 'busy'], ant: ['lazy', 'idle'], level: 'medium', tags: ['common11plus'] },
  { word: 'inept', meaning: 'having no skill', pos: 'adj', syn: ['clumsy', 'incompetent'], ant: ['able', 'skilled'], level: 'medium', tags: ['common11plus'] },
  { word: 'infamous', meaning: 'famous for something bad', pos: 'adj', syn: ['notorious', 'disreputable'], ant: ['celebrated', 'honourable'], level: 'hard', tags: ['common11plus'] },
  { word: 'ingenuity', meaning: 'cleverness in planning', pos: 'noun', syn: ['creativity', 'inventiveness'], ant: ['stupidity', 'dullness'], level: 'hard', tags: ['common11plus'] },
  { word: 'innate', meaning: 'existing from birth', pos: 'adj', syn: ['inborn', 'natural'], ant: ['acquired', 'learned'], level: 'hard', tags: ['common11plus'] },
  { word: 'insightful', meaning: 'showing clear understanding', pos: 'adj', syn: ['perceptive', 'astute'], ant: ['dull', 'obtuse'], level: 'hard', tags: ['common11plus'] },
  { word: 'insolent', meaning: 'showing rude lack of respect', pos: 'adj', syn: ['rude', 'cheeky'], ant: ['polite', 'respectful'], level: 'hard', tags: ['common11plus'] },
  { word: 'integrity', meaning: 'honesty and strong morals', pos: 'noun', syn: ['honesty', 'uprightness'], ant: ['dishonesty', 'corruption'], level: 'hard', tags: ['common11plus'] },
  { word: 'intrepid', meaning: 'fearless', pos: 'adj', syn: ['brave', 'bold'], ant: ['fearful', 'timid'], level: 'hard', tags: ['common11plus'] },
  { word: 'intricate', meaning: 'very detailed', pos: 'adj', syn: ['complex', 'elaborate'], ant: ['simple', 'plain'], level: 'hard', tags: ['common11plus'] },
  { word: 'intuitive', meaning: 'understood without reasoning', pos: 'adj', syn: ['instinctive', 'automatic'], ant: ['logical', 'calculated'], level: 'hard', tags: ['common11plus'] },
  { word: 'inventive', meaning: 'creative at producing new ideas', pos: 'adj', syn: ['creative', 'original'], ant: ['unimaginative', 'dull'], level: 'hard', tags: ['common11plus'] },
  { word: 'jovial', meaning: 'cheerful and friendly', pos: 'adj', syn: ['cheerful', 'jolly'], ant: ['miserable', 'gloomy'], level: 'medium', tags: ['common11plus'] },
  { word: 'judicious', meaning: 'showing good judgement', pos: 'adj', syn: ['wise', 'sensible'], ant: ['foolish', 'reckless'], level: 'hard', tags: ['common11plus'] },
  { word: 'keen', meaning: 'eager and enthusiastic', pos: 'adj', syn: ['eager', 'enthusiastic'], ant: ['reluctant', 'apathetic'], level: 'easy', tags: ['common11plus'] },
  { word: 'kinship', meaning: 'family relationship or close connection', pos: 'noun', syn: ['connection', 'affinity'], ant: ['distance', 'separation'], level: 'medium', tags: ['common11plus'] },
  { word: 'lament', meaning: 'to express grief', pos: 'verb', syn: ['mourn', 'grieve'], ant: ['celebrate', 'rejoice'], level: 'medium', tags: ['common11plus'] },
  { word: 'lavish', meaning: 'rich and generous', pos: 'adj', syn: ['extravagant', 'sumptuous'], ant: ['meagre', 'stingy'], level: 'hard', tags: ['common11plus'] },
  { word: 'legible', meaning: 'easy to read', pos: 'adj', syn: ['readable', 'clear'], ant: ['illegible', 'unclear'], level: 'easy', tags: ['common11plus'] },
  { word: 'lenient', meaning: 'not strict', pos: 'adj', syn: ['soft', 'forgiving'], ant: ['strict', 'harsh'], level: 'medium', tags: ['common11plus'] },
  { word: 'lethargic', meaning: 'sluggish and without energy', pos: 'adj', syn: ['sluggish', 'drowsy'], ant: ['energetic', 'lively'], level: 'medium', tags: ['common11plus'] },
  { word: 'liberate', meaning: 'to set free', pos: 'verb', syn: ['free', 'release'], ant: ['confine', 'imprison'], level: 'medium', tags: ['common11plus'] },
  { word: 'lucid', meaning: 'clear and easy to understand', pos: 'adj', syn: ['clear', 'coherent'], ant: ['confusing', 'muddled'], level: 'hard', tags: ['common11plus'] },
  { word: 'luminous', meaning: 'giving off light', pos: 'adj', syn: ['glowing', 'radiant'], ant: ['dark', 'dim'], level: 'medium', tags: ['common11plus'] },
  { word: 'magnify', meaning: 'to make something appear larger', pos: 'verb', syn: ['enlarge', 'amplify'], ant: ['reduce', 'shrink'], level: 'medium', tags: ['common11plus'] },
  { word: 'majestic', meaning: 'impressive and grand', pos: 'adj', syn: ['grand', 'stately'], ant: ['ordinary', 'common'], level: 'medium', tags: ['common11plus'] },
  { word: 'malevolent', meaning: 'having evil intentions', pos: 'adj', syn: ['malicious', 'spiteful'], ant: ['benevolent', 'kind'], level: 'hard', tags: ['common11plus'] },
  { word: 'meticulous', meaning: 'very careful and precise', pos: 'adj', syn: ['careful', 'thorough'], ant: ['careless', 'sloppy'], level: 'hard', tags: ['common11plus'] },
  { word: 'mirthful', meaning: 'full of laughter', pos: 'adj', syn: ['cheerful', 'jolly'], ant: ['sad', 'sorrowful'], level: 'medium', tags: ['common11plus'] },
  { word: 'modest', meaning: 'not boastful', pos: 'adj', syn: ['humble', 'unassuming'], ant: ['arrogant', 'vain'], level: 'easy', tags: ['common11plus'] },
  { word: 'momentous', meaning: 'very important', pos: 'adj', syn: ['significant', 'historic'], ant: ['insignificant', 'trivial'], level: 'hard', tags: ['common11plus'] },
  { word: 'mournful', meaning: 'full of sadness', pos: 'adj', syn: ['sad', 'sorrowful'], ant: ['joyful', 'cheerful'], level: 'medium', tags: ['common11plus'] },
  { word: 'mundane', meaning: 'ordinary and dull', pos: 'adj', syn: ['ordinary', 'common'], ant: ['exciting', 'remarkable'], level: 'medium', tags: ['common11plus'] },
  { word: 'murmur', meaning: 'to speak softly', pos: 'verb', syn: ['whisper', 'mutter'], ant: ['shout', 'yell'], level: 'easy', tags: ['common11plus'] },
  { word: 'nimble', meaning: 'quick and light in movement', pos: 'adj', syn: ['agile', 'spry'], ant: ['slow', 'clumsy'], level: 'medium', tags: ['common11plus'] },
  { word: 'notable', meaning: 'worthy of attention', pos: 'adj', syn: ['remarkable', 'striking'], ant: ['ordinary', 'unremarkable'], level: 'medium', tags: ['common11plus'] },
  { word: 'nurture', meaning: 'to care for and encourage growth', pos: 'verb', syn: ['rear', 'foster'], ant: ['neglect', 'ignore'], level: 'medium', tags: ['common11plus'] },
  { word: 'oblivious', meaning: 'not aware of', pos: 'adj', syn: ['unaware', 'ignorant'], ant: ['aware', 'alert'], level: 'medium', tags: ['common11plus'] },
  { word: 'obstinate', meaning: 'stubborn', pos: 'adj', syn: ['stubborn', 'unyielding'], ant: ['flexible', 'yielding'], level: 'hard', tags: ['common11plus'] },
  { word: 'obvious', meaning: 'easy to see', pos: 'adj', syn: ['clear', 'evident'], ant: ['hidden', 'uncertain'], level: 'easy', tags: ['common11plus'] },
  { word: 'optimistic', meaning: 'hopeful about the future', pos: 'adj', syn: ['hopeful', 'positive'], ant: ['pessimistic', 'gloomy'], level: 'medium', tags: ['common11plus'] },
  { word: 'ornate', meaning: 'decorated with complex patterns', pos: 'adj', syn: ['elaborate', 'fancy'], ant: ['plain', 'simple'], level: 'hard', tags: ['common11plus'] },
  { word: 'oust', meaning: 'to force someone out', pos: 'verb', syn: ['expel', 'remove'], ant: ['install', 'appoint'], level: 'hard', tags: ['common11plus'] },
  { word: 'outlandish', meaning: 'very strange', pos: 'adj', syn: ['bizarre', 'eccentric'], ant: ['ordinary', 'normal'], level: 'hard', tags: ['common11plus'] },
  { word: 'overjoyed', meaning: 'extremely happy', pos: 'adj', syn: ['ecstatic', 'delighted'], ant: ['miserable', 'downcast'], level: 'easy', tags: ['common11plus'] },
  { word: 'palatable', meaning: 'pleasant to taste', pos: 'adj', syn: ['tasty', 'agreeable'], ant: ['unpalatable', 'disagreeable'], level: 'medium', tags: ['common11plus'] },
  { word: 'peculiar', meaning: 'strange or unusual', pos: 'adj', syn: ['odd', 'unusual'], ant: ['ordinary', 'normal'], level: 'medium', tags: ['common11plus'] },
  { word: 'perilous', meaning: 'very dangerous', pos: 'adj', syn: ['dangerous', 'hazardous'], ant: ['safe', 'secure'], level: 'hard', tags: ['common11plus'] },
  { word: 'persevere', meaning: 'to keep trying despite difficulty', pos: 'verb', syn: ['persist', 'continue'], ant: ['quit', 'give up'], level: 'medium', tags: ['common11plus'] },
  { word: 'persuade', meaning: 'to convince someone', pos: 'verb', syn: ['convince', 'urge'], ant: ['deter', 'discourage'], level: 'medium', tags: ['common11plus'] },
  { word: 'pinnacle', meaning: 'the highest point', pos: 'noun', syn: ['peak', 'summit'], ant: ['base', 'bottom'], level: 'hard', tags: ['common11plus'] },
  { word: 'plausible', meaning: 'seeming reasonable', pos: 'adj', syn: ['believable', 'credible'], ant: ['unlikely', 'implausible'], level: 'medium', tags: ['common11plus'] },
  { word: 'plight', meaning: 'a difficult situation', pos: 'noun', syn: ['predicament', 'difficulty'], ant: ['blessing', 'advantage'], level: 'hard', tags: ['common11plus'] },
  { word: 'plucky', meaning: 'brave and determined', pos: 'adj', syn: ['brave', 'courageous'], ant: ['cowardly', 'fearful'], level: 'medium', tags: ['common11plus'] },
  { word: 'ponder', meaning: 'to think about carefully', pos: 'verb', syn: ['consider', 'contemplate'], ant: ['ignore', 'dismiss'], level: 'medium', tags: ['common11plus'] },
  { word: 'porous', meaning: 'full of tiny holes', pos: 'adj', syn: ['permeable', 'spongy'], ant: ['solid', 'impervious'], level: 'hard', tags: ['common11plus'] },
  { word: 'potent', meaning: 'very powerful', pos: 'adj', syn: ['powerful', 'strong'], ant: ['weak', 'ineffective'], level: 'medium', tags: ['common11plus'] },
  { word: 'precise', meaning: 'exact and accurate', pos: 'adj', syn: ['exact', 'accurate'], ant: ['approximate', 'inexact'], level: 'medium', tags: ['common11plus'] },
  { word: 'predicament', meaning: 'a tricky situation', pos: 'noun', syn: ['difficulty', 'dilemma'], ant: ['solution', 'advantage'], level: 'medium', tags: ['common11plus'] },
  { word: 'premature', meaning: 'too early', pos: 'adj', syn: ['early', 'untimely'], ant: ['late', 'overdue'], level: 'medium', tags: ['common11plus'] },
  { word: 'presume', meaning: 'to suppose something is true', pos: 'verb', syn: ['assume', 'suppose'], ant: ['doubt', 'question'], level: 'medium', tags: ['common11plus'] },
  { word: 'prevail', meaning: 'to succeed or win', pos: 'verb', syn: ['triumph', 'succeed'], ant: ['fail', 'lose'], level: 'medium', tags: ['common11plus'] },
  { word: 'pristine', meaning: 'fresh and clean', pos: 'adj', syn: ['spotless', 'pure'], ant: ['dirty', 'spoiled'], level: 'medium', tags: ['common11plus'] },
  { word: 'proclaim', meaning: 'to announce officially', pos: 'verb', syn: ['announce', 'declare'], ant: ['conceal', 'hide'], level: 'medium', tags: ['common11plus'] },
  { word: 'profound', meaning: 'deep and thoughtful', pos: 'adj', syn: ['deep', 'intense'], ant: ['shallow', 'superficial'], level: 'hard', tags: ['common11plus'] },
  { word: 'prolific', meaning: 'producing a lot', pos: 'adj', syn: ['productive', 'fertile'], ant: ['barren', 'unproductive'], level: 'hard', tags: ['common11plus'] },
  { word: 'prompt', meaning: 'done without delay', pos: 'adj', syn: ['swift', 'punctual'], ant: ['slow', 'tardy'], level: 'easy', tags: ['common11plus'] },
  { word: 'prudent', meaning: 'careful and sensible', pos: 'adj', syn: ['sensible', 'wise'], ant: ['reckless', 'careless'], level: 'medium', tags: ['common11plus'] },
  { word: 'radiant', meaning: 'shining brightly', pos: 'adj', syn: ['bright', 'glowing'], ant: ['dull', 'dim'], level: 'easy', tags: ['common11plus'] },
  { word: 'rash', meaning: 'acting without thinking', pos: 'adj', syn: ['impetuous', 'hasty'], ant: ['careful', 'cautious'], level: 'medium', tags: ['common11plus'] },
  { word: 'reassure', meaning: 'to make someone feel less worried', pos: 'verb', syn: ['comfort', 'encourage'], ant: ['alarm', 'worry'], level: 'medium', tags: ['common11plus'] },
  { word: 'rebuke', meaning: 'to scold sharply', pos: 'verb', syn: ['scold', 'reprimand'], ant: ['praise', 'commend'], level: 'medium', tags: ['common11plus'] },
  { word: 'recluse', meaning: 'a person who lives alone', pos: 'noun', syn: ['hermit', 'loner'], ant: ['socialite', 'extrovert'], level: 'hard', tags: ['common11plus'] },
  { word: 'refined', meaning: 'elegant and cultured', pos: 'adj', syn: ['cultured', 'polished'], ant: ['crude', 'vulgar'], level: 'medium', tags: ['common11plus'] },
  { word: 'relentless', meaning: 'never giving up', pos: 'adj', syn: ['unwavering', 'persistent'], ant: ['yielding', 'soft'], level: 'hard', tags: ['common11plus'] },
  { word: 'relish', meaning: 'to enjoy greatly', pos: 'verb', syn: ['enjoy', 'savour'], ant: ['dislike', 'detest'], level: 'medium', tags: ['common11plus'] },
  { word: 'reluctant', meaning: 'unwilling or hesitant', pos: 'adj', syn: ['unwilling', 'hesitant'], ant: ['eager', 'keen'], level: 'easy', tags: ['common11plus'] },
  { word: 'remorse', meaning: 'deep regret', pos: 'noun', syn: ['regret', 'repentance'], ant: ['indifference', 'shamelessness'], level: 'hard', tags: ['common11plus'] },
  { word: 'resilient', meaning: 'able to recover quickly', pos: 'adj', syn: ['tough', 'hardy'], ant: ['fragile', 'weak'], level: 'medium', tags: ['common11plus'] },
  { word: 'resolute', meaning: 'firm and determined', pos: 'adj', syn: ['determined', 'steadfast'], ant: ['uncertain', 'wavering'], level: 'hard', tags: ['common11plus'] },
  { word: 'revere', meaning: 'to respect deeply', pos: 'verb', syn: ['respect', 'honour'], ant: ['disrespect', 'despise'], level: 'medium', tags: ['common11plus'] },
  { word: 'robust', meaning: 'strong and healthy', pos: 'adj', syn: ['strong', 'sturdy'], ant: ['weak', 'frail'], level: 'medium', tags: ['common11plus'] },
  { word: 'sagacious', meaning: 'wise and clever', pos: 'adj', syn: ['wise', 'shrewd'], ant: ['foolish', 'silly'], level: 'hard', tags: ['common11plus'] },
  { word: 'scarce', meaning: 'hard to find', pos: 'adj', syn: ['rare', 'limited'], ant: ['abundant', 'plentiful'], level: 'medium', tags: ['common11plus'] },
  { word: 'scrutinise', meaning: 'to examine closely', pos: 'verb', syn: ['inspect', 'examine'], ant: ['glance', 'ignore'], level: 'hard', tags: ['common11plus'] },
  { word: 'serene', meaning: 'calm and peaceful', pos: 'adj', syn: ['calm', 'tranquil'], ant: ['stormy', 'agitated'], level: 'easy', tags: ['common11plus'] },
  { word: 'shrewd', meaning: 'having sharp judgement', pos: 'adj', syn: ['astute', 'clever'], ant: ['stupid', 'slow'], level: 'hard', tags: ['common11plus'] },
  { word: 'skeptical', meaning: 'doubting or questioning', pos: 'adj', syn: ['doubtful', 'suspicious'], ant: ['trusting', 'convinced'], level: 'medium', tags: ['common11plus'] },
  { word: 'sleek', meaning: 'smooth and glossy', pos: 'adj', syn: ['smooth', 'polished'], ant: ['rough', 'dull'], level: 'easy', tags: ['common11plus'] },
  { word: 'solitary', meaning: 'alone', pos: 'adj', syn: ['alone', 'isolated'], ant: ['sociable', 'together'], level: 'medium', tags: ['common11plus'] },
  { word: 'somber', meaning: 'dark or gloomy', pos: 'adj', syn: ['gloomy', 'solemn'], ant: ['bright', 'cheerful'], level: 'medium', tags: ['common11plus'] },
  { word: 'soothe', meaning: 'to calm or comfort', pos: 'verb', syn: ['calm', 'ease'], ant: ['upset', 'agitate'], level: 'easy', tags: ['common11plus'] },
  { word: 'sparse', meaning: 'thinly spread', pos: 'adj', syn: ['scant', 'few'], ant: ['dense', 'abundant'], level: 'hard', tags: ['common11plus'] },
  { word: 'sprightly', meaning: 'full of energy', pos: 'adj', syn: ['lively', 'energetic'], ant: ['dull', 'sluggish'], level: 'hard', tags: ['common11plus'] },
  { word: 'spurious', meaning: 'false or fake', pos: 'adj', syn: ['false', 'bogus'], ant: ['genuine', 'authentic'], level: 'hard', tags: ['common11plus'] },
  { word: 'squalid', meaning: 'extremely dirty', pos: 'adj', syn: ['filthy', 'grim'], ant: ['clean', 'pristine'], level: 'hard', tags: ['common11plus'] },
  { word: 'stalwart', meaning: 'loyal and hardworking', pos: 'adj', syn: ['steadfast', 'loyal'], ant: ['weak', 'unreliable'], level: 'hard', tags: ['common11plus'] },
  { word: 'steadfast', meaning: 'firm and unwavering', pos: 'adj', syn: ['loyal', 'resolute'], ant: ['fickle', 'inconstant'], level: 'hard', tags: ['common11plus'] },
  { word: 'stifle', meaning: 'to stop something from developing', pos: 'verb', syn: ['suppress', 'smother'], ant: ['encourage', 'release'], level: 'medium', tags: ['common11plus'] },
  { word: 'sturdy', meaning: 'strongly built', pos: 'adj', syn: ['robust', 'solid'], ant: ['fragile', 'weak'], level: 'medium', tags: ['common11plus'] },
  { word: 'subtle', meaning: 'delicate and hard to notice', pos: 'adj', syn: ['fine', 'delicate'], ant: ['obvious', 'blunt'], level: 'hard', tags: ['common11plus'] },
  { word: 'succinct', meaning: 'briefly and clearly expressed', pos: 'adj', syn: ['concise', 'brief'], ant: ['wordy', 'rambling'], level: 'hard', tags: ['common11plus'] },
  { word: 'sufficient', meaning: 'enough', pos: 'adj', syn: ['enough', 'adequate'], ant: ['insufficient', 'lacking'], level: 'easy', tags: ['common11plus'] },
  { word: 'sullen', meaning: 'bad-tempered and gloomy', pos: 'adj', syn: ['sulky', 'morose'], ant: ['cheerful', 'bright'], level: 'medium', tags: ['common11plus'] },
  { word: 'summon', meaning: 'to call someone to come', pos: 'verb', syn: ['call', 'beckon'], ant: ['dismiss', 'send away'], level: 'medium', tags: ['common11plus'] },
  { word: 'superfluous', meaning: 'unnecessary', pos: 'adj', syn: ['unneeded', 'excess'], ant: ['necessary', 'essential'], level: 'hard', tags: ['common11plus'] },
  { word: 'surpass', meaning: 'to go beyond', pos: 'verb', syn: ['exceed', 'outdo'], ant: ['fall short', 'lose'], level: 'medium', tags: ['common11plus'] },
  { word: 'tangible', meaning: 'able to be touched', pos: 'adj', syn: ['solid', 'real'], ant: ['intangible', 'abstract'], level: 'hard', tags: ['common11plus'] },
  { word: 'tedious', meaning: 'boring and too long', pos: 'adj', syn: ['dull', 'monotonous'], ant: ['interesting', 'lively'], level: 'medium', tags: ['common11plus'] },
  { word: 'tenacious', meaning: 'holding on firmly', pos: 'adj', syn: ['determined', 'persistent'], ant: ['weak', 'yielding'], level: 'hard', tags: ['common11plus'] },
  { word: 'tepid', meaning: 'slightly warm', pos: 'adj', syn: ['lukewarm', 'mild'], ant: ['hot', 'chilly'], level: 'medium', tags: ['common11plus'] },
  { word: 'thrifty', meaning: 'using money carefully', pos: 'adj', syn: ['frugal', 'economical'], ant: ['extravagant', 'wasteful'], level: 'medium', tags: ['common11plus'] },
  { word: 'timid', meaning: 'shy and fearful', pos: 'adj', syn: ['shy', 'fearful'], ant: ['brave', 'bold'], level: 'easy', tags: ['common11plus'] },
  { word: 'tranquil', meaning: 'calm and peaceful', pos: 'adj', syn: ['calm', 'serene'], ant: ['noisy', 'agitated'], level: 'medium', tags: ['common11plus'] },
  { word: 'transient', meaning: 'lasting only a short time', pos: 'adj', syn: ['temporary', 'brief'], ant: ['permanent', 'lasting'], level: 'hard', tags: ['common11plus'] },
  { word: 'treacherous', meaning: 'dangerously unstable', pos: 'adj', syn: ['dangerous', 'deceitful'], ant: ['safe', 'trustworthy'], level: 'hard', tags: ['common11plus'] },
  { word: 'trivial', meaning: 'of little importance', pos: 'adj', syn: ['unimportant', 'minor'], ant: ['serious', 'significant'], level: 'medium', tags: ['common11plus'] },
  { word: 'truculent', meaning: 'eager to fight', pos: 'adj', syn: ['aggressive', 'hostile'], ant: ['gentle', 'peaceful'], level: 'hard', tags: ['common11plus'] },
  { word: 'undaunted', meaning: 'not discouraged by difficulty', pos: 'adj', syn: ['brave', 'fearless'], ant: ['afraid', 'timid'], level: 'hard', tags: ['common11plus'] },
  { word: 'uneasy', meaning: 'worried or anxious', pos: 'adj', syn: ['anxious', 'restless'], ant: ['calm', 'relaxed'], level: 'medium', tags: ['common11plus'] },
  { word: 'unique', meaning: 'one of a kind', pos: 'adj', syn: ['distinct', 'special'], ant: ['common', 'ordinary'], level: 'easy', tags: ['common11plus'] },
  { word: 'valiant', meaning: 'brave and determined', pos: 'adj', syn: ['brave', 'courageous'], ant: ['cowardly', 'fearful'], level: 'medium', tags: ['common11plus'] },
  { word: 'venerable', meaning: 'deserving respect because of age', pos: 'adj', syn: ['respected', 'revered'], ant: ['disreputable', 'disgraced'], level: 'hard', tags: ['common11plus'] },
  { word: 'versatile', meaning: 'able to do many things', pos: 'adj', syn: ['adaptable', 'flexible'], ant: ['limited', 'inflexible'], level: 'medium', tags: ['common11plus'] },
  { word: 'vex', meaning: 'to annoy', pos: 'verb', syn: ['annoy', 'irritate'], ant: ['please', 'delight'], level: 'medium', tags: ['common11plus'] },
  { word: 'vigorous', meaning: 'strong and energetic', pos: 'adj', syn: ['energetic', 'robust'], ant: ['weak', 'feeble'], level: 'medium', tags: ['common11plus'] },
  { word: 'vivid', meaning: 'very bright or clear', pos: 'adj', syn: ['bright', 'intense'], ant: ['dull', 'faded'], level: 'medium', tags: ['common11plus'] },
  { word: 'wane', meaning: 'to become weaker', pos: 'verb', syn: ['diminish', 'decline'], ant: ['grow', 'increase'], level: 'hard', tags: ['common11plus'] },
  { word: 'wary', meaning: 'careful because of danger', pos: 'adj', syn: ['cautious', 'alert'], ant: ['reckless', 'careless'], level: 'medium', tags: ['common11plus'] },
  { word: 'wholesome', meaning: 'good for you', pos: 'adj', syn: ['healthy', 'beneficial'], ant: ['harmful', 'unhealthy'], level: 'easy', tags: ['common11plus'] },
  { word: 'wilt', meaning: 'to become limp', pos: 'verb', syn: ['droop', 'sag'], ant: ['flourish', 'perk up'], level: 'medium', tags: ['common11plus'] },
  { word: 'wily', meaning: 'clever at gaining advantage', pos: 'adj', syn: ['cunning', 'sly'], ant: ['honest', 'naive'], level: 'medium', tags: ['common11plus'] },
  { word: 'wither', meaning: 'to dry up and die', pos: 'verb', syn: ['shrivel', 'fade'], ant: ['flourish', 'bloom'], level: 'medium', tags: ['common11plus'] },
  { word: 'zealous', meaning: 'showing great enthusiasm', pos: 'adj', syn: ['enthusiastic', 'passionate'], ant: ['indifferent', 'apathetic'], level: 'hard', tags: ['common11plus'] },
  { word: 'zestful', meaning: 'full of energy and enjoyment', pos: 'adj', syn: ['lively', 'energetic'], ant: ['dull', 'spiritless'], level: 'medium', tags: ['common11plus'] },
];
